on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 18
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build
        working-directory: backend/
        run: ./gradlew clean build
      - name: Build Docker image
        working-directory: backend/
        run: |
          docker build -t ghcr.io/noahvdaa/hangartotal/backend:latest .
          docker push ghcr.io/noahvdaa/hangartotal/backend
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build Docker image
        working-directory: frontend/
        run: |
          docker build -t ghcr.io/noahvdaa/hangartotal/frontend:latest .
          docker push ghcr.io/noahvdaa/hangartotal/frontend
